In [19]:
# Slade Brooks
# brooksl@mail.uc.edu
# 02.07.2023

# calculate V profile for HW3

In [20]:
# import thing I need
import streamFunc
import numpy as np
import matplotlib.pyplot as plt

In [21]:
# set up mesh of x and ys
xs = np.linspace(-5, 5, 100)
ys = np.linspace(-1, 1, 100)

# make Vinf
Vinf = 10

In [22]:
# calculate function at each point
# make array
vals = np.zeros((len(xs),len(ys)),dtype="float64")

# stream fxn
stream = streamFunc.streamFunc()

# loop thru mesh and calc at each point
for i in range(0, len(xs)):
    for k in range(0, len(ys)):
        # uniform flow
        vals[i, k] = Vinf
        # source 1 - A=1Vinf,x=-2
        vals[i, k] = stream.sourcesinkPsi(-2, 0, xs[i], ys[k], 10)
        # source 2 - A=2Vinf,x=-1
        vals[i, k] += stream.sourcesinkPsi(-1, 0, xs[i], ys[k], 20)
        # source 3 - A=1Vinf,x=0
        vals[i, k] += stream.sourcesinkPsi(0, 0, xs[i], ys[k], 10)
        # source 4 - A=-3Vinf,x=1
        vals[i, k] += stream.sourcesinkPsi(1, 0, xs[i], ys[k], -30)
        # source 5 - A=-1Vinf,x=2
        vals[i, k] += stream.sourcesinkPsi(2, 0, xs[i], ys[k], 10)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


TypeError: 'float' object is not callable

In [ ]:
# contourf it
plt.contourf(xs, ys, vals)