### Slade Brooks
##### brooksl@mail.uc.edu
##### 04.07.2023
# AeroComputing Assignment 10

This code computes eigensystems.

In [64]:
# import stuff
import numpy as np

# Matrix A

In [65]:
# define matrix A
A = np.array([[5, 3, 0, 0, 0],
              [0, 5, 0, 0, 0],
              [0, 0, 5, 0, 0],
              [0, 0, 0, 5, 1],
              [0, 0, 0, 0, 5]])

In [66]:
# compute eigensystem
[vals, vecs] = np.linalg.eig(A)

print("The eigenvalues are: ", vals)
print("The eigenvectors are: \n", vecs)

The eigenvalues are:  [5. 5. 5. 5. 5.]
The eigenvectors are: 
 [[ 1.00000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  3.70074342e-16  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.11022302e-15]]


In [67]:
# verify eigensystem - Ax = lambdax for each vector/value (x vector, labmda value)
for i in range(len(A)):
    Ax = np.dot(A.copy(), vecs[:,i])
    lambdax = np.dot(vals[i], vecs[:,i])
    print((Ax - lambdax).round())

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


An eigensystem is defined as Ax = lambdax where x is an eigenvector and lambda is the corresponding eigenvalue. We can verify the solution by showing that Ax-lambdax is 0 for each eigenvector/value combination.

# Matrix B

In [68]:
# define B matrix
B = np.array([[51, 2, 3, 5, 7, 11],
              [1, 52, 3, 5, 7, 11],
              [1, 2, 53, 5, 7, 11],
              [1, 2, 3, 55, 7, 11],
              [1, 2, 3, 5, 57, 11],
              [1, 2, 3, 5, 7, 61]])

In [69]:
# compute eigensystem
[vals, vecs] = np.linalg.eig(B)

print("The eigenvalues are: ", vals)
print("The eigenvectors are: \n", vecs)

The eigenvalues are:  [50. 79. 50. 50. 50. 50.]
The eigenvectors are: 
 [[-0.9968264   0.40824829 -0.13808215 -0.03161848  0.20684395 -0.17524922]
 [ 0.03560094  0.40824829  0.6964458  -0.31475671  0.6739762  -0.28686365]
 [ 0.03560094  0.40824829  0.10249803  0.9249406   0.3945283  -0.22250713]
 [ 0.03560094  0.40824829 -0.68145361 -0.18985152  0.44267549 -0.25362209]
 [ 0.03560094  0.40824829  0.10249803 -0.06469068 -0.27509771 -0.61066133]
 [ 0.03560094  0.40824829  0.10249803 -0.06469068 -0.27509771  0.63265797]]


In [70]:
# verify eigensystem - Ax = lambdax for each vector/value (x vector, labmda value)
for i in range(len(B)):
    Bx = np.dot(B.copy(), vecs[:,i])
    lambdax = np.dot(vals[i], vecs[:,i])
    print((Bx - lambdax).round())

[ 0. -0. -0. -0. -0. -0.]
[0. 0. 0. 0. 0. 0.]
[ 0. -0.  0.  0.  0.  0.]
[-0.  0. -0.  0.  0.  0.]
[-0.  0.  0.  0. -0. -0.]
[ 0.  0.  0.  0. -0.  0.]


An eigensystem is defined as Bx = lambdax where x is an eigenvector and lambda is the corresponding eigenvalue. We can verify the solution by showing that Bx-lambdax is 0 for each eigenvector/value combination.