### Slade Brooks
### M13801712
### brooksl@mail.uc.edu
### Final Exam

In [2]:
import numpy as np
import sys
import matplotlib.pyplot as plt
from scipy import integrate as integrate
# import custom modules
sys.path.append("..//lib//")
import pyvot

# Question 1

## Part A

In [3]:
# create A matrix
A = np.array([[31, 3, 5, 6, 9, 10],
              [1, 33, 5, 6, 9, 10],
              [1, 3, 35, 6, 9, 10],
              [1, 3, 5, 36, 9, 10],
              [1, 3, 5, 6, 39, 10],
              [1, 3, 5, 6, 9, 40]])

In [6]:
# find b from Ax=b so that x is all 5s
x = np.array([[5],[5],[5],[5],[5],[5]])
b = np.dot(A.copy(), x.copy())

print("The right side matrix b such that x is all 5s is: \n", b)

The right side matrix b such that x is all 5s is: 
 [[320]
 [320]
 [320]
 [320]
 [320]
 [320]]


## Part B

In [10]:
# solve Ax=b with gausspivot
x = pyvot.gaussPivot(A.copy(), b.copy())

# print it
print("The solution x = \n", x.copy())

The solution x = 
 [[5]
 [5]
 [5]
 [5]
 [5]
 [5]]


## Part C

In [11]:
# print solution
print("The solution x = \n", x.copy())

# get residual and show it is 0 (solve Ax=b)
res = np.linalg.norm(np.dot(A.copy(), x.copy()) - b.copy())

print("The residual is:", res)

The solution x = 
 [[5]
 [5]
 [5]
 [5]
 [5]
 [5]]
The residual norm is: 0.0


We know that this x matrix is a solution because the residual of the Ax - B calculation is so small. The residual is 0, therefore this matrix must be the solution. (this is because Ax=B, so Ax-B must be 0 for a correct solution)