### Slade Brooks
### M13801712
### brooksl@mail.uc.edu
### Final Exam

In [2]:
import numpy as np
import sys
import matplotlib.pyplot as plt
from scipy import integrate as integrate
# import custom modules
sys.path.append("..//lib//")
import pyvot

# Question 1

## Part A

In [3]:
# create A matrix
A = np.array([[31, 3, 5, 6, 9, 10],
              [1, 33, 5, 6, 9, 10],
              [1, 3, 35, 6, 9, 10],
              [1, 3, 5, 36, 9, 10],
              [1, 3, 5, 6, 39, 10],
              [1, 3, 5, 6, 9, 40]])

In [6]:
# find b from Ax=b so that x is all 5s
x = np.array([[5],[5],[5],[5],[5],[5]])
b = np.dot(A.copy(), x.copy())

print("The right side matrix b such that x is all 5s is: \n", b)

The right side matrix b such that x is all 5s is: 
 [[320]
 [320]
 [320]
 [320]
 [320]
 [320]]


## Part B

In [10]:
# solve Ax=b with gausspivot
x = pyvot.gaussPivot(A.copy(), b.copy())

# print it
print("The solution x = \n", x.copy())

The solution x = 
 [[5]
 [5]
 [5]
 [5]
 [5]
 [5]]


## Part C

In [11]:
# print solution
print("The solution x = \n", x.copy())

# get residual and show it is 0 (solve Ax=b -> Ax-b = 0)
res = np.linalg.norm(np.dot(A.copy(), x.copy()) - b.copy())
print("The residual is:", res)

The solution x = 
 [[5]
 [5]
 [5]
 [5]
 [5]
 [5]]
The residual norm is: 0.0


We know that this x matrix is a solution because the residual of the Ax - B calculation is so small. The residual is 0, therefore this matrix must be the solution. (this is because Ax=B, so Ax-B must be 0 for a correct solution)

# Question 2

## Part A

In [12]:
# compute eigensystem
[vals, vecs] = np.linalg.eig(A.copy())

print("The eigenvalues are: ", vals)
print("The eigenvectors are: \n", vecs)

The eigenvalues are:  [30. 64. 30. 30. 30. 30.]
The eigenvectors are: 
 [[-0.99771219  0.40824829  0.5626329  -0.56329077 -0.1919516   0.17461255]
 [ 0.0302337   0.40824829  0.80263683  0.55112017 -0.23417387 -0.00694525]
 [ 0.0302337   0.40824829 -0.09901811  0.5544123  -0.28738022 -0.5342004 ]
 [ 0.0302337   0.40824829 -0.09901811 -0.15448525  0.55083436 -0.4999621 ]
 [ 0.0302337   0.40824829 -0.09901811 -0.15448525 -0.58289951 -0.10900671]
 [ 0.0302337   0.40824829 -0.09901811 -0.15448525  0.42724637  0.64980581]]


## Part B

In [13]:
# verify eigensystem - Ax = lambdax for each vector/value (x vector, labmda value)
for i in range(len(A)):
    Ax = np.dot(A.copy(), vecs[:,i])
    lambdax = np.dot(vals[i], vecs[:,i])
    print((Ax - lambdax).round())

[0. 0. 0. 0. 0. 0.]
[-0.  0.  0.  0.  0.  0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0.  0.  0. -0.  0. -0.]
[-0. -0. -0. -0. -0.  0.]


An eigensystem is defined as Ax = lambdax where x is an eigenvector and lambda is the corresponding eigenvalue. We can verify the solution by showing that Ax-lambdax is 0 for each eigenvector/value combination.

# Question 3