### Slade Brooks
### brooksl@mail.uc.edu
### Exam 1
### Question 1

In [84]:
import numpy as np
import sys

# import custom modules
sys.path.append("..//lib//")
import pyvot

In [85]:
# M13 801712

# create a matrix with last six
nums = np.array([[8, 0, 1, 7, 1, 2],
                [1, 4, 3, 4, 5, 6],
                [1, 2, 4, 4, 5, 6],
                [1, 2, 3, 4, 5, 6],
                [1, 2, 3, 4, 4, 6,],
                [1, 2, 3, 4, 5, 5]], dtype="float64")

# print matrix
print(nums.copy())

[[8. 0. 1. 7. 1. 2.]
 [1. 4. 3. 4. 5. 6.]
 [1. 2. 4. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 4. 6.]
 [1. 2. 3. 4. 5. 5.]]


In [86]:
# find determinant
det = np.linalg.det(nums.copy())
print("The determinant is {:.2f}.".format(det))

The determinant is 50.00.


Since the determinant is not zero and the matrix is 6x6 elements (square), the matrix "nums" must be nonsingular.

In [87]:
# create solution vector all +2
b = np.array([[2],
              [2],
              [2],
              [2],
              [2],
              [2]], dtype="float64")

# print dat
print("The solution vector is:", b.copy())

The solution vector is: [[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]


In [88]:
# find solution x using gaussPivot :)
x = pyvot.gaussPivot(nums.copy(), b.copy())

# print it
print("The solution x =", x.copy())

The solution x = [[-2.40000000e-01]
 [ 0.00000000e+00]
 [ 4.55476113e-17]
 [ 5.60000000e-01]
 [-0.00000000e+00]
 [ 0.00000000e+00]]


In [89]:
# calculate the residual's norm
norm = np.linalg.norm(np.dot(nums.copy(), x.copy()) - b.copy())

print("The residual norm is:", norm)

The residual norm is: 4.965068306494546e-16


We know that this x matrix is a solution because the residual of the Ax - B calculation is so small. The result is E-16, which is essentially zero meaning the residual is 0 and the solution is correct.