### Slade Brooks
### brooksl@mail.uc.edu
### Exam 1
### Question 1

In [3]:
import numpy as np

In [13]:
# M13 801712

# create a matrix with last six
nums = np.array([[8, 0, 1, 7, 1, 2],
                [1, 4, 3, 4, 5, 6],
                [1, 2, 4, 4, 5, 6],
                [1, 2, 3, 4, 5, 6],
                [1, 2, 3, 4, 4, 6,],
                [1, 2, 3, 4, 5, 5]], dtype="float64")

# print matrix
print(nums)

[[8. 0. 1. 7. 1. 2.]
 [1. 4. 3. 4. 5. 6.]
 [1. 2. 4. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 4. 6.]
 [1. 2. 3. 4. 5. 5.]]


In [18]:
# find determinant
det = np.linalg.det(nums)
print("The determinant is {:.2f}.".format(det))

The determinant is 50.00.


Since the determinant is not zero and the matrix is 6x6 elements, the matrix "nums" must be nonsingular.

In [21]:
# create solution vector all +2
b = np.array([[2],
              [2],
              [2],
              [2],
              [2],
              [2]], dtype="float64")

# print dat
print("The solution vector is:", b)

The solution vector is: [[2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]
